#spring:
#  data:
#    mongodb:
#       uri: mongodb://localhost:27017/test1
#
#

server:
  error:
    include-message: always
    include-binding-errors: always

default:
  password: 123456

paging:
  default:
    page: 0
    size: 20

google:
  verifyUrl: https://www.googleapis.com/oauth2/v3/tokeninfo?access_token=
